[package]
name = "iftree"
version = "0.1.0"
authors = ["Benjamin Fischer <benjamin.fischer@evolutics.info>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/evolutics/iftree"
repository = "https://github.com/evolutics/iftree"
readme = true
keywords = ["include", "file", "tree", "static", "embed"]
categories = ["filesystem", "web-programming"]
description = """
Include file data from many files in your Rust code for self-contained binaries."""

[lib]
proc-macro = true

[dependencies]
ignore = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = "1.0"
toml = "0.5"

[dev-dependencies]
actix-web = "3.3"
async-std = { version = "1.9", features = ["attributes"] }
handlebars = "3.5"
mime_guess = "2.0"
once_cell = "1.7"
tide = "0.16"
tokio = { version = "1.5", features = ["full"] }
warp = "0.3"
