[package]
name = "iftree"
version = "0.1.0"
authors = ["Benjamin Fischer <benjamin.fischer@evolutics.info>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/evolutics/iftree"
repository = "https://github.com/evolutics/iftree"
readme = true
keywords = ["include", "file", "tree", "static", "embed"]
categories = ["filesystem", "web-programming"]
description = """
Include file trees in your code, like `include_bytes!` and `include_str!` for \
path patterns, with support for custom macros."""

[lib]
proc-macro = true

[dependencies]
ignore = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = "1.0"
toml = "0.5"

[dev-dependencies]
mime_guess = "2.0"
once_cell = "1.7"
