[package]
name = "iftree"
version = "1.0.0"
authors = ["Benjamin Fischer <benjamin.fischer@evolutics.info>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/evolutics/iftree"
repository = "https://github.com/evolutics/iftree"
keywords = ["include", "directory", "folder", "file", "embed"]
categories = ["filesystem", "web-programming"]
description = """
Include many files in your Rust code for self-contained binaries."""

[lib]
proc-macro = true

[dependencies]
ignore = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
serde = { version = "1.0", features = ["derive"] }
syn = { version = "1.0", features = ["default", "extra-traits"] }
toml = "0.5"
unicode-xid = "0.2"

[dev-dependencies]
actix-web = "3.3"
async-std = { version = "1.9", features = ["attributes"] }
handlebars = "4.1"
include-flate = { version = "0.1", features = ["stable"] }
lazy_static = "1.4"
mime_guess = "2.0"
once_cell = "1.8"
regex = "1.5"
tempfile = "3.2"
tide = "0.16"
tokio = { version = "1.8", features = ["full"] }
warp = "0.3"
