on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: cachix/install-nix-action@v25
      # See also https://github.com/actions-rs/meta/issues/21.
      - uses: Swatinem/rust-cache@v2
      - run: python scripts/test.py
